version: '3.8'
services:
  postgres:
    container_name: postgres
    image: postgres:14.1-alpine
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=example
    ports:
      - '5432:5432'
    command: -p 5432
    volumes: 
      - postgres:/var/lib/postgresql/data
  backend:
    container_name: backend
    build:
      context: ./
    image: backend
    depends_on:
      - postgres
    ports:
      - 8080:8080
    environment:
      HTTP_PORT: ":8080"
      LOG_LEVEL: debug
      POSTGRES_HOST: postgres
      POSTGRES_PORT: 5432
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DATABASE: example
volumes:
  postgres: