apiVersion: v1
kind: Service
metadata:
  namespace: dell
  labels:
    app: backend
  name: backend
spec:
  ports:
    - name: "8080"
      port: 8080
      targetPort: 8080
  selector:
    app: backend
status:
  loadBalancer: {}
