apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: dell
  labels:
    app: backend
  name: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - env:
            - name: HTTP_PORT
              value: :8080
            - name: LOG_LEVEL
              value: debug
            - name: POSTGRES_DATABASE
              value: example
            - name: POSTGRES_HOST
              value: postgres
            - name: POSTGRES_PASSWORD
              value: postgres
            - name: POSTGRES_PORT
              value: "5432"
            - name: POSTGRES_USER
              value: postgres
          image: dellicon/mono-psql-go
          name: backend
          ports:
            - containerPort: 8080
          resources: {}
      restartPolicy: Always
status: {}
